issues with GET response, no authentication
AndresChapo/survivors pull request #20
Opened 2023-06-02 16:34 UTC by lautaroAguilar

## Descripción

## Cambios

## Notas
Estuvimos tratando de resolver problemas de authentification con Alexis, pero no pudimos, hice el push para que el pueda revisarlos en su local

2023-06-04 15:43 UTC, AndresChapo approved these changes

2023-06-08 19:02 UTC, lautaroAguilar commented
-sacamos Axios por fetch + limpieza de código 
-ya toma los datos del backend y los muestra

2023-06-08 20:17 UTC, alexis2013 reviewed
Nice job! Solo me quedo una duda, y fijate si podes actualizar la descrpcion y las notas que quedaron con las anteriores

2023-06-09 12:54 UTC, NextDoor95 commented on survivors/api/api.js
> +async function getUser() {
Si, deberíamos borrar la que no usemos para evitar confusiones a futuro, es eso nomas por que en el resto del código no veo nada mal

2023-06-09 12:56 UTC, NextDoor95 requested changes
Habría que borrar la función GetUser que no se use y está duplicada

2023-06-10 19:21 UTC, AndresChapo approved these changes

2023-06-10 19:22 UTC, merged