[CRYP-59] Add acreen with signup and signin modal
AndresChapo/survivors pull request #25
Opened 2023-06-11 21:08 UTC by alexis2013

## Descripción

## Cambios

## Notas

2023-06-11 22:28 UTC, lautaroAguilar commented on survivors/components/SignUp/signup.jsx
>              console.log(response.data);
quedó un console.log rebelde

2023-06-11 22:30 UTC, lautaroAguilar commented on survivors/components/SignUp/signup.jsx
>              console.log(response.data);
quedó un console.log rebelde

2023-06-11 22:38 UTC, lautaroAguilar approved these changes
Genial Ale, super práctica la integración de la nueva pantalla, buenisimo

2023-06-11 23:58 UTC, AndresChapo commented on survivors/components/SignUp/signup.jsx
>              const response = await axios({
Pense que no ibamos a usar mas axios

2023-06-12 00:00 UTC, AndresChapo commented on survivors/components/SignIn/signin.jsx
> +export default SignIn
Podemos aprovechar para cambiarle el nombre a Login ?

2023-06-12 00:00 UTC, AndresChapo commented on survivors/components/SignIn/signin.jsx
> +//import { RiLockPasswordFill } from "react-icons/ri";
Yo los borraria directamente.

2023-06-12 00:04 UTC, alexis2013 commented on survivors/components/SignIn/signin.jsx
> +export default SignIn
Si, joya

2023-06-12 00:05 UTC, alexis2013 commented on survivors/components/SignUp/signup.jsx
>              const response = await axios({
Si, lo actualizo

2023-06-12 00:22 UTC, alexis2013 commented on survivors/components/SignUp/signup.jsx
>              console.log(response.data);
borrado!

2023-06-12 00:22 UTC, alexis2013 commented on survivors/components/SignUp/signup.jsx
>              const response = await axios({
done

2023-06-12 00:22 UTC, alexis2013 commented on survivors/components/SignIn/signin.jsx
> +export default SignIn
Done

2023-06-12 00:22 UTC, alexis2013 commented on survivors/components/SignIn/signin.jsx
> +//import { RiLockPasswordFill } from "react-icons/ri";
Listo

2023-06-12 00:39 UTC, AndresChapo requested changes

2023-06-12 00:39 UTC, AndresChapo commented on survivors/components/SignUp/signup.jsx
> +            };
La respuesta del BE cuando sale bien es 201.

2023-06-12 00:40 UTC, alexis2013 commented on survivors/components/SignUp/signup.jsx
> +            };
Done

2023-06-12 00:44 UTC, AndresChapo approved these changes
excelente!

2023-06-12 00:48 UTC, merged

2023-06-12 17:06 UTC, NextDoor95 reviewed
Te quedó genial! yo no uso ' ; ' por que no es necesario, pero entiendo que se sigue usando por buenas practicas así que lo voy a usar mientras no me olvide jajajaj te quedó todo genial!