Cryp 41 qr photo
AndresChapo/survivors pull request #29
Opened 2023-06-16 03:23 UTC by NextDoor95

## Descripción

## Cambios

## Notas

2023-06-16 17:15 UTC, alexis2013 requested changes
Nice job! 
Falta agregarle la descripcion y las notas, y conectar con el backend para enviar el archivo, pero es un re avance!!

2023-06-16 17:15 UTC, alexis2013 commented on survivors/components/QR-photo/Qrphoto.jsx
> +            {
- Habiamos decidido usar fetch por los problemas con axios y el login, fijate si podes usarlo aca para tener una sola libreria, pero si elegiste axios por el archivo en el payload o por si tuviste algun problema, agregale un comentario y dejalo.
- Tiene que llamar a `{base_url}/transactions/qr, el payload tiene que ser content type form-data 
```
{
  "file": archivo.jpg // o cualquier extension, type: file
}
```
y la response seria:
```
{
    "response": {
        "link": <drive url>
    }
}
```

2023-06-16 21:34 UTC, NextDoor95 commented
> Nice job! Falta agregarle la descripcion y las notas, y conectar con el backend para enviar el archivo, pero es un re avance!!

Subí el PR con todo comentado jajaj done!

2023-06-16 21:37 UTC, NextDoor95 commented on survivors/next.config.js
Este es el código que modifiqué para que no me de problemas al usar la carpeta /App con Next.js

2023-06-16 22:00 UTC, AndresChapo commented on survivors/components/QR-photo/Qrphoto.jsx
> +                        screenshotQuality={0.8}
Muy bueno. en gral... che lo de la quality sera lo que hizo q arranque mas lento en algunos celus?

2023-06-16 23:31 UTC, NextDoor95 commented on survivors/components/QR-photo/Qrphoto.jsx
> +                        screenshotQuality={0.8}
Gracias!, no creo que sea eso, por default si no se pone la calidad que toma es 0.91 (1 es el máximo), lo bajé intencionalmente un poco por ese tema, podemos bajarlo más pero no es recomendable

2023-06-19 01:03 UTC, alexis2013 approved these changes
Tremendo!

2023-06-19 05:13 UTC, merged